-- =============================================================================
-- Promotions & campaigns on live data — validation suite
-- (migration `…_promotions_live`: admin_save_promotion, admin_save_campaign,
--  quote_basket, promotion_daily_usage, promotion_code_attempts).
-- =============================================================================
-- Requires all migrations + at least one active EUR product without variants.
-- ONE transaction, ALWAYS rolled back by raising `ALL PROMOTIONS LIVE TESTS PASSED`
-- (or `FAIL: ...`).
--
--   PL1 customers and read-only staff cannot save a promotion or a campaign
--   PL2 a shared-code promotion is saved live in one call (code, English text, Paris time)
--   PL3 editing a live promotion keeps it live; a changed code switches the old one off;
--       a code of another promotion is refused (23505); a promotion cannot go live incomplete
--   PL4 unique codes are generated by the save
--   PL5 switching to automatic switches its codes off
--   PL6 quote_basket: automatic promotion, typed code, wrong code (counted, then locked),
--       loyalty reward + code refused; visitors never read a code
--   PL7 campaigns: saved with ordered products and an English translation, products replaced
--   PL8 a draft may wait for its shared code; going live without one is refused
-- =============================================================================

do $$
declare
  mgr  uuid := '00000000-0000-4000-a000-0000000b0001';
  vwr  uuid := '00000000-0000-4000-a000-0000000b0002';
  cst  uuid := '00000000-0000-4000-a000-0000000b0003';
  v_prod uuid;
  v_price numeric;
  v_p1 uuid; v_p2 uuid; v_p3 uuid; v_p4 uuid; v_camp uuid;
  v_cnt int; v_state text; v_txt text; v_num numeric; v_ts timestamptz;
  v_json jsonb;
  v_items jsonb;
  passed text[] := '{}';
  base jsonb;
begin
  insert into auth.users (id, aud, role, email, raw_user_meta_data, created_at, updated_at) values
    (mgr, 'authenticated', 'authenticated', 'promo.mgr.test@example.invalid', '{"first_name":"Mia"}', now(), now()),
    (vwr, 'authenticated', 'authenticated', 'promo.vwr.test@example.invalid', '{"first_name":"Val"}', now(), now()),
    (cst, 'authenticated', 'authenticated', 'promo.cst.test@example.invalid', '{"first_name":"Cleo"}', now(), now());
  update public.profiles set role = 'manager' where id = mgr;
  update public.profiles set role = 'viewer' where id = vwr;

  select p.id, p.price into v_prod, v_price from public.products p
   where p.status = 'active' and p.currency = 'EUR' and p.product_type <> 'gift_card' and p.price >= 5
     and not exists (select 1 from public.product_variants v where v.product_id = p.id and v.is_active)
   order by p.created_at limit 1;
  if v_prod is null then raise exception 'FAIL setup: no active EUR product without variants'; end if;
  v_items := jsonb_build_array(jsonb_build_object('product_id', v_prod, 'variant_id', null, 'quantity', 2));

  base := jsonb_build_object(
    'name', 'Test promo', 'internal_description', '',
    'title', jsonb_build_object('fr', 'Dix pour cent', 'en', 'Ten percent'),
    'description', jsonb_build_object('fr', '', 'en', ''),
    'type', 'percentage', 'percent_off', 10,
    'applies_to', 'all', 'customer_eligibility', 'all',
    'max_uses_per_customer', 1, 'combinable', false, 'exclude_discounted_products', true,
    'activation', 'code', 'code_kind', 'shared', 'code', 'plvalid10',
    'starts_at', '2026-07-01T10:00', 'ends_at', null, 'timezone', 'Europe/Paris', 'lifecycle', 'live');

  -- PL1 -------------------------------------------------------------------------------
  perform set_config('role', 'authenticated', true);
  foreach v_txt in array array['customer', 'viewer'] loop
    perform set_config('request.jwt.claims',
      json_build_object('sub', case v_txt when 'customer' then cst else vwr end, 'role', 'authenticated')::text, true);
    v_state := null;
    begin perform public.admin_save_promotion(base);
    exception when others then v_state := sqlstate; end;
    if v_state is distinct from '42501' then raise exception 'FAIL PL1: % saved a promotion (%)', v_txt, v_state; end if;
    v_state := null;
    begin perform public.admin_save_campaign('{}'::jsonb);
    exception when others then v_state := sqlstate; end;
    if v_state is distinct from '42501' then raise exception 'FAIL PL1: % saved a campaign (%)', v_txt, v_state; end if;
  end loop;
  passed := array_append(passed, 'PL1 customers and viewers refused');

  -- PL2 -------------------------------------------------------------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', mgr, 'role', 'authenticated')::text, true);
  v_p1 := public.admin_save_promotion(base);
  select count(*) into v_cnt from public.promotions where id = v_p1 and lifecycle = 'live' and title = 'Dix pour cent';
  if v_cnt <> 1 then raise exception 'FAIL PL2: promotion not saved live'; end if;
  select count(*) into v_cnt from public.promotion_codes where promotion_id = v_p1 and code = 'PLVALID10' and is_active;
  if v_cnt <> 1 then raise exception 'FAIL PL2: shared code missing'; end if;
  select count(*) into v_cnt from public.promotion_translations where promotion_id = v_p1 and locale = 'en' and title = 'Ten percent';
  if v_cnt <> 1 then raise exception 'FAIL PL2: English text missing'; end if;
  select starts_at into v_ts from public.promotions where id = v_p1;
  if v_ts <> '2026-07-01 08:00:00+00' then raise exception 'FAIL PL2: Paris summer time not applied (%)', v_ts; end if;
  select count(*) into v_cnt from public.promotion_overview where id = v_p1 and status = 'active';
  if v_cnt <> 1 then raise exception 'FAIL PL2: not active in the overview'; end if;
  passed := array_append(passed, 'PL2 shared-code promotion saved live in one call (summer time honoured)');

  -- PL3 -------------------------------------------------------------------------------
  v_p2 := public.admin_save_promotion(base || jsonb_build_object('id', v_p1, 'code', 'plvalid20', 'applies_to', 'products',
                                     'product_ids', jsonb_build_array(v_prod)));
  select count(*) into v_cnt from public.promotions where id = v_p1 and lifecycle = 'live' and applies_to = 'products';
  if v_cnt <> 1 then raise exception 'FAIL PL3: edited promotion not live / not scoped'; end if;
  select count(*) into v_cnt from public.promotion_products where promotion_id = v_p1 and role = 'eligible' and product_id = v_prod;
  if v_cnt <> 1 then raise exception 'FAIL PL3: scope not saved'; end if;
  select count(*) into v_cnt from public.promotion_codes where promotion_id = v_p1 and is_active and code = 'PLVALID20';
  if v_cnt <> 1 then raise exception 'FAIL PL3: new code not active'; end if;
  select count(*) into v_cnt from public.promotion_codes where promotion_id = v_p1 and is_active and code = 'PLVALID10';
  if v_cnt <> 0 then raise exception 'FAIL PL3: old code still active'; end if;
  -- the same code on another promotion
  v_state := null;
  begin perform public.admin_save_promotion(base || jsonb_build_object('name', 'Other', 'code', 'PLVALID20'));
  exception when others then v_state := sqlstate; end;
  if v_state is distinct from '23505' then raise exception 'FAIL PL3: duplicate code accepted (%)', v_state; end if;
  -- live without its products
  v_state := null;
  begin perform public.admin_save_promotion(base || jsonb_build_object('id', v_p1, 'code', 'PLVALID20', 'applies_to', 'products', 'product_ids', '[]'::jsonb));
  exception when others then v_state := sqlstate; end;
  if v_state is distinct from '23514' then raise exception 'FAIL PL3: live promotion without products accepted (%)', v_state; end if;
  select count(*) into v_cnt from public.promotions where id = v_p1 and lifecycle = 'live' and applies_to = 'products';
  if v_cnt <> 1 then raise exception 'FAIL PL3: refused save changed the promotion'; end if;
  passed := array_append(passed, 'PL3 live edit, code swap, duplicate code and incomplete publish refused');

  -- PL4 -------------------------------------------------------------------------------
  v_p3 := public.admin_save_promotion(base || jsonb_build_object('name', 'Unique', 'code_kind', 'unique', 'code', '',
                                     'unique_code_count', 3, 'unique_code_prefix', 'plu', 'lifecycle', 'live'));
  select count(*) into v_cnt from public.promotion_codes where promotion_id = v_p3 and is_active and max_uses = 1 and code like 'PLU-%';
  if v_cnt <> 3 then raise exception 'FAIL PL4: expected 3 unique codes, got %', v_cnt; end if;
  passed := array_append(passed, 'PL4 unique codes generated by the save');

  -- PL5 -------------------------------------------------------------------------------
  perform public.admin_save_promotion(base || jsonb_build_object('id', v_p1, 'activation', 'automatic', 'applies_to', 'all', 'name', 'Auto'));
  select count(*) into v_cnt from public.promotion_codes where promotion_id = v_p1 and is_active;
  if v_cnt <> 0 then raise exception 'FAIL PL5: codes still active on an automatic promotion'; end if;
  select count(*) into v_cnt from public.promotions where id = v_p1 and lifecycle = 'live' and activation = 'automatic' and code_kind is null;
  if v_cnt <> 1 then raise exception 'FAIL PL5: not automatic'; end if;
  passed := array_append(passed, 'PL5 switching to automatic switches the codes off');

  -- PL6: quote_basket ----------------------------------------------------------------------
  perform set_config('role', 'anon', true);
  perform set_config('request.jwt.claims', json_build_object('role', 'anon')::text, true);
  v_json := public.quote_basket(v_items);
  if not (v_json ->> 'ok')::boolean or (v_json ->> 'goods_discount')::numeric <> round(v_price * 2 * 0.10, 2) then
    raise exception 'FAIL PL6: automatic promotion not quoted (%)', v_json;
  end if;
  v_json := public.quote_basket(v_items, array['NOPE-NOPE']);
  if (v_json ->> 'ok')::boolean or v_json ->> 'error' <> 'promotion_code_invalid' then
    raise exception 'FAIL PL6: unknown code not refused (%)', v_json;
  end if;
  -- the typed code of the live code promotion (PL4's first unique code is private: use a shared one)
  perform set_config('role', 'authenticated', true);
  perform set_config('request.jwt.claims', json_build_object('sub', mgr, 'role', 'authenticated')::text, true);
  v_p4 := public.admin_save_promotion(base || jsonb_build_object('name', 'Shared 25', 'percent_off', 25, 'code', 'plshare25',
                                     'combinable', false));
  perform set_config('role', 'anon', true);
  perform set_config('request.jwt.claims', json_build_object('role', 'anon')::text, true);
  v_json := public.quote_basket(v_items, array['plshare25']);
  if not (v_json ->> 'ok')::boolean or (v_json ->> 'goods_discount')::numeric <> round(v_price * 2 * 0.25, 2)
     or v_json #>> '{discounts,0,code}' <> 'PLSHARE25' then
    raise exception 'FAIL PL6: typed code not quoted as the best option (%)', v_json;
  end if;
  v_json := public.quote_basket(v_items, array['plshare25']);
  v_state := null;
  begin
    select count(*) into v_cnt from public.promotion_codes;
  exception when others then v_state := sqlstate;
  end;
  if v_state is distinct from '42501' then raise exception 'FAIL PL6: a visitor reads codes (%)', v_state; end if;
  perform set_config('role', 'authenticated', true);
  perform set_config('request.jwt.claims', json_build_object('sub', cst, 'role', 'authenticated')::text, true);
  select count(*) into v_cnt from public.promotion_codes;
  if v_cnt <> 0 then raise exception 'FAIL PL6: a customer reads codes'; end if;
  v_json := public.quote_basket(v_items, array['PLSHARE25'], null, true);
  if (v_json ->> 'ok')::boolean or v_json ->> 'error' <> 'loyalty_reward_unavailable' then
    raise exception 'FAIL PL6: reward + code accepted (%)', v_json;
  end if;
  -- ten refusals lock the codes for the caller
  for i in 1..10 loop
    v_json := public.quote_basket(v_items, array['WRONG' || i::text]);
  end loop;
  v_json := public.quote_basket(v_items, array['PLSHARE25']);
  if v_json ->> 'error' is distinct from 'too_many_attempts' then
    raise exception 'FAIL PL6: guessing not throttled (%)', v_json;
  end if;
  v_json := public.quote_basket(v_items);
  if not (v_json ->> 'ok')::boolean then raise exception 'FAIL PL6: throttle blocked the codeless quote (%)', v_json; end if;
  passed := array_append(passed, 'PL6 quote: automatic, typed code, refusals counted then locked, reward + code refused, codes unreadable');

  -- PL7: campaigns -------------------------------------------------------------------------------
  perform set_config('request.jwt.claims', json_build_object('sub', mgr, 'role', 'authenticated')::text, true);
  v_camp := public.admin_save_campaign(jsonb_build_object(
    'name', 'Camp', 'title', jsonb_build_object('fr', 'Soldes', 'en', 'Sale'),
    'description', jsonb_build_object('fr', '', 'en', ''),
    'starts_at', '2026-11-20T00:00', 'ends_at', '2026-11-30T23:59', 'timezone', 'Europe/Paris',
    'theme', 'noir', 'product_ids', jsonb_build_array(v_prod), 'lifecycle', 'live'));
  select count(*) into v_cnt from public.campaign_products where campaign_id = v_camp and product_id = v_prod;
  if v_cnt <> 1 then raise exception 'FAIL PL7: campaign products missing'; end if;
  select count(*) into v_cnt from public.campaign_translations where campaign_id = v_camp and locale = 'en' and title = 'Sale';
  if v_cnt <> 1 then raise exception 'FAIL PL7: campaign English text missing'; end if;
  perform public.admin_save_campaign(jsonb_build_object(
    'id', v_camp, 'name', 'Camp', 'title', jsonb_build_object('fr', 'Soldes', 'en', ''),
    'description', jsonb_build_object('fr', '', 'en', ''),
    'starts_at', '2026-11-20T00:00', 'ends_at', '2026-11-30T23:59', 'timezone', 'Europe/Paris',
    'theme', 'noir', 'product_ids', '[]'::jsonb, 'lifecycle', 'paused'));
  select count(*) into v_cnt from public.campaign_products where campaign_id = v_camp;
  select lifecycle into v_txt from public.campaigns where id = v_camp;
  if v_cnt <> 0 or v_txt <> 'paused' then raise exception 'FAIL PL7: campaign update not applied'; end if;
  select count(*) into v_cnt from public.campaign_translations where campaign_id = v_camp;
  if v_cnt <> 0 then raise exception 'FAIL PL7: emptied English text kept'; end if;
  passed := array_append(passed, 'PL7 campaigns saved with products and English text, replaced on edit');

  -- PL8: a draft waits for its code; going live without one is refused ----------------------------
  perform set_config('role', 'authenticated', true);
  perform set_config('request.jwt.claims', json_build_object('sub', mgr, 'role', 'authenticated')::text, true);
  v_p1 := public.admin_save_promotion(base || jsonb_build_object('name', 'Waiting', 'code', '', 'lifecycle', 'draft'));
  select count(*) into v_cnt from public.promotions where id = v_p1 and lifecycle = 'draft' and activation = 'code';
  if v_cnt <> 1 then raise exception 'FAIL PL8: draft without code not saved'; end if;
  v_state := null;
  begin perform public.admin_save_promotion(base || jsonb_build_object('id', v_p1, 'code', '', 'lifecycle', 'live'));
  exception when others then v_state := sqlstate; end;
  if v_state is distinct from '23514' then raise exception 'FAIL PL8: live without a code accepted (%)', v_state; end if;
  passed := array_append(passed, 'PL8 a draft may wait for its code, publishing without one is refused');

  raise exception 'ALL PROMOTIONS LIVE TESTS PASSED (% checks): %', array_length(passed, 1), array_to_string(passed, ' | ');
end;
$$;
