"""Writes webapp/src/lib/documents/assets.generated.ts.

The PDF documents (`src/lib/documents/`) are written by hand, without a PDF
library, and set in the PDF standard fonts. This script produces the two
things such a writer cannot compute at run time:

- the advance widths of Helvetica and Helvetica-Bold for the WinAnsi code
  points 32-255 (Adobe's metrics, as shipped by reportlab), so text can be
  wrapped and right-aligned;
- the Global Toothgems wordmark as a PDF soft mask (8-bit alpha, deflated),
  drawn black through it.

Run from webapp/: python3 scripts/document-assets.py (needs reportlab, Pillow).
"""

import base64
import zlib
from pathlib import Path

from PIL import Image
from reportlab.pdfbase import pdfmetrics

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / "src/assets/logo-wordmark-black.png"
OUT = ROOT / "src/lib/documents/assets.generated.ts"
LOGO_WIDTH = 720  # px: 300 dpi at 61 mm, wider than the documents print it
INK = 0x11  # the wordmark's grey level (#111111, the documents' ink)


def widths(font_name: str) -> str:
    font = pdfmetrics.getFont(font_name)
    assert font.encoding.name == "WinAnsiEncoding"
    values = [font.widths[code] for code in range(32, 256)]
    rows = [", ".join(str(v) for v in values[i : i + 16]) for i in range(0, len(values), 16)]
    return "[\n  " + ",\n  ".join(rows) + ",\n]"


def logo() -> tuple[int, int, str, str]:
    image = Image.open(LOGO).convert("RGBA")
    height = round(image.height * LOGO_WIDTH / image.width)
    alpha = image.resize((LOGO_WIDTH, height), Image.LANCZOS).getchannel("A")
    data = base64.b64encode(zlib.compress(alpha.tobytes(), 9)).decode("ascii")
    # The ink as an image of the same size: some readers mishandle a mask larger than its image.
    ink = base64.b64encode(zlib.compress(bytes([INK]) * (LOGO_WIDTH * height), 9)).decode("ascii")
    return LOGO_WIDTH, height, data, ink


def main() -> None:
    width, height, data, ink = logo()
    chunks = [data[i : i + 120] for i in range(0, len(data), 120)]
    OUT.write_text(
        "// Generated by scripts/document-assets.py — do not edit by hand.\n\n"
        "/** Advance widths (1/1000 em) of Helvetica for WinAnsi codes 32-255. */\n"
        f"export const HELVETICA_WIDTHS: readonly number[] = {widths('Helvetica')};\n\n"
        "/** Advance widths (1/1000 em) of Helvetica-Bold for WinAnsi codes 32-255. */\n"
        f"export const HELVETICA_BOLD_WIDTHS: readonly number[] = {widths('Helvetica-Bold')};\n\n"
        "/** The wordmark: its alpha channel and its ink, 8-bit grey each, deflated (base64). */\n"
        f"export const WORDMARK = {{\n  width: {width},\n  height: {height},\n  ink: \"{ink}\",\n  mask:\n    "
        + " +\n    ".join(f'"{c}"' for c in chunks)
        + ",\n} as const;\n"
    )


if __name__ == "__main__":
    main()
