-- =============================================================================
-- Migration — Product variants edited from the back office (colours, boxes…)
-- =============================================================================
-- Until now the admin form only edited gem pack × stone-size options
-- (`…_gem_pack_stone_size_options`). Every other kind of variant — a mirror
-- in two colours, capsules in boxes of 50 or 100, a gem in 2 or 3 mm — could
-- only be created in SQL. The product form gains a generic "Variants" editor:
-- one row per variant, each with its own name (fr + en), optional colour
-- swatch, optional price, stock and photos.
--
-- No table or column changes: a variant is a `product_variants` row with its
-- own `inventory_items` row, and a photo points at its variant through the
-- existing `product_media.variant_id` (migration 002).
--
-- admin_save_product() gains two OPTIONAL inputs:
--
--   custom_variants   absent        variants left exactly as they are;
--                     [] or a list  the complete, ordered list of the
--                                   product's variants:
--                     [{ id, name, name_en, swatch, price, track_inventory,
--                        quantity_on_hand, low_stock_threshold }]
--       id        uuid, generated by the browser for a new variant (like the
--                 product id), so a photo can point at a variant created in
--                 the same save;
--       name      default-language (fr) name, 1–200 characters;
--       name_en   English name; empty = the storefront falls back to French;
--       swatch    '#rrggbb' (lower case) or null — the colour dot the
--                 storefront shows; kept in attributes.swatch, every other
--                 attribute (e.g. {"quantity": 50}) is preserved;
--       price     decimal string or null (null = the product price).
--     A new variant's SKU is derived here from the product SKU and the French
--     name (TOO-MIR-01-BLEU), made unique with a suffix; an existing SKU never
--     changes on rename (orders and stock sheets refer to it). A variant left
--     out of the list is deleted, or deactivated when an order references it
--     (order_items.variant_id is ON DELETE RESTRICT), like the gem options.
--     Cannot be combined with `variants` (the pack/SS options), nor used on a
--     product that sells active pack/SS options.
--
--   media[].variant_id  when the key is present: the variant this photo
--                       shows (null = the whole product). Absent = the link
--                       is left as it is, so an older admin never clears it.
--
-- The function returns `custom_variants` (ids, in position order) when the
-- payload carried the key: the admin checks for it, so a front end deployed
-- before this migration fails loudly instead of silently dropping variants.
-- Everything else is unchanged from `…_gem_free_pack_sizes.sql`.
-- =============================================================================

create or replace function public.admin_save_product(p_product jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_id        uuid := (p_product ->> 'id')::uuid;
  v_price     text := p_product ->> 'price';
  v_compare   text := nullif(p_product ->> 'compare_at_price', '');
  v_inventory jsonb := coalesce(p_product -> 'inventory', '{}'::jsonb);
  v_media     jsonb := coalesce(p_product -> 'media', '[]'::jsonb);
  v_variants  jsonb := p_product -> 'variants';
  v_custom    jsonb := p_product -> 'custom_variants';
  v_en        jsonb := p_product -> 'translations' -> 'en';
  v_slug      text;
  v_base      text;
  v_n         integer := 1;
  v_keep      uuid[];
  v_removed   text[];
  v_item      jsonb;
  v_media_id  uuid;
  v_position  integer := 0;
  -- variants
  v_sku        text;
  v_pack       integer;
  v_ss         integer;
  v_vprice     text;
  v_name_fr    text;
  v_name_en    text;
  v_vsku       text;
  v_variant_id uuid;
  v_variant_ids uuid[] := '{}';
  -- custom variants
  v_custom_ids uuid[] := '{}';
  v_swatch     text;
  v_owner      uuid;
  v_code       text;
  v_media_variant uuid;
begin
  if not private.has_permission('manage_products') then
    raise exception 'admin_save_product: permission denied' using errcode = '42501';
  end if;
  if v_id is null then
    raise exception 'admin_save_product: id is required' using errcode = '22023';
  end if;
  if v_price is null or v_price !~ '^\d{1,10}(\.\d{1,2})?$' then
    raise exception 'admin_save_product: invalid price' using errcode = '22023';
  end if;
  if v_compare is not null and v_compare !~ '^\d{1,10}(\.\d{1,2})?$' then
    raise exception 'admin_save_product: invalid compare_at_price' using errcode = '22023';
  end if;
  if jsonb_typeof(v_media) <> 'array' then
    raise exception 'admin_save_product: media must be an array' using errcode = '22023';
  end if;
  if v_variants is not null and jsonb_typeof(v_variants) = 'null' then
    v_variants := null;
  end if;
  if v_variants is not null and jsonb_typeof(v_variants) <> 'array' then
    raise exception 'admin_save_product: variants must be an array' using errcode = '22023';
  end if;
  if v_custom is not null and jsonb_typeof(v_custom) = 'null' then
    v_custom := null;
  end if;
  if v_custom is not null and jsonb_typeof(v_custom) <> 'array' then
    raise exception 'admin_save_product: custom_variants must be an array' using errcode = '22023';
  end if;
  if v_variants is not null and v_custom is not null then
    raise exception 'admin_save_product: send either variants or custom_variants, not both' using errcode = '22023';
  end if;

  -- 1. Product row ------------------------------------------------------------
  if exists (select 1 from public.products where id = v_id) then
    update public.products
       set category_id       = (p_product ->> 'category_id')::uuid,
           sku               = nullif(p_product ->> 'sku', ''),
           name              = p_product ->> 'name',
           short_description = nullif(p_product ->> 'short_description', ''),
           description       = nullif(p_product ->> 'description', ''),
           price             = v_price::numeric(12, 2),
           compare_at_price  = v_compare::numeric(12, 2),
           status            = p_product ->> 'status',
           metadata          = metadata || coalesce(p_product -> 'metadata', '{}'::jsonb)
     where id = v_id
    returning slug into v_slug;
  else
    -- The slug is the storefront URL: set once, made unique with a suffix.
    v_base := p_product ->> 'slug';
    v_slug := v_base;
    while exists (select 1 from public.products where slug = v_slug) loop
      v_n := v_n + 1;
      v_slug := v_base || '-' || v_n;
    end loop;

    insert into public.products
      (id, category_id, sku, name, slug, short_description, description,
       price, compare_at_price, status, metadata)
    values
      (v_id, (p_product ->> 'category_id')::uuid, nullif(p_product ->> 'sku', ''),
       p_product ->> 'name', v_slug,
       nullif(p_product ->> 'short_description', ''), nullif(p_product ->> 'description', ''),
       v_price::numeric(12, 2), v_compare::numeric(12, 2),
       p_product ->> 'status', coalesce(p_product -> 'metadata', '{}'::jsonb));
  end if;

  -- 2. English translation (published on save; absent = storefront falls back
  --    to French) ---------------------------------------------------------------
  if coalesce(trim(v_en ->> 'name'), '') <> '' then
    v_base := nullif(v_en ->> 'slug', '');
    v_n := 1;
    if not exists (select 1 from public.product_translations where product_id = v_id and locale = 'en')
       and v_base is not null then
      v_slug := v_base;
      while exists (select 1 from public.product_translations where locale = 'en' and slug = v_slug) loop
        v_n := v_n + 1;
        v_slug := v_base || '-' || v_n;
      end loop;
    else
      v_slug := null;  -- keep the existing English URL
    end if;

    insert into public.product_translations
      (product_id, locale, name, slug, short_description, description, status)
    values
      (v_id, 'en', v_en ->> 'name', v_slug,
       nullif(v_en ->> 'short_description', ''), nullif(v_en ->> 'description', ''), 'published')
    on conflict (product_id, locale) do update
       set name              = excluded.name,
           short_description = excluded.short_description,
           description       = excluded.description,
           status            = 'published';
  else
    delete from public.product_translations where product_id = v_id and locale = 'en';
  end if;

  -- 3. Pack / stone-size options (only when the payload carries them) ---------
  if v_variants is not null then
    -- Only pack/SS variants are managed here: a product whose variants are
    -- something else (colours, boxes…) must not lose them to this editor.
    if exists (
      select 1 from public.product_variants pv
       where pv.product_id = v_id
         and (pv.attributes = '{}'::jsonb
              or exists (select 1 from jsonb_object_keys(pv.attributes) k where k not in ('pack', 'ss')))
    ) then
      raise exception 'admin_save_product: this product has other kinds of variants' using errcode = '22023';
    end if;

    v_sku := (select sku from public.products where id = v_id);
    v_position := 0;

    for v_item in select value from jsonb_array_elements(v_variants) loop
      if jsonb_typeof(v_item) <> 'object' then
        raise exception 'admin_save_product: invalid variant' using errcode = '22023';
      end if;
      if coalesce(v_item ->> 'pack', '') !~ '^\d{0,5}$' then
        raise exception 'admin_save_product: invalid pack size' using errcode = '22023';
      end if;
      if coalesce(v_item ->> 'ss', '') !~ '^\d{1,2}$' and coalesce(v_item ->> 'ss', '') <> '' then
        raise exception 'admin_save_product: invalid stone size' using errcode = '22023';
      end if;
      v_pack := nullif(v_item ->> 'pack', '')::integer;
      v_ss   := nullif(v_item ->> 'ss', '')::integer;
      if v_pack is null and v_ss is null then
        raise exception 'admin_save_product: a variant needs a pack or a stone size' using errcode = '22023';
      end if;
      if v_pack is not null and v_pack not between 1 and 10000 then
        raise exception 'admin_save_product: pack size must be between 1 and 10000' using errcode = '22023';
      end if;
      if v_ss is not null and v_ss not between 1 and 60 then
        raise exception 'admin_save_product: invalid stone size' using errcode = '22023';
      end if;
      v_vprice := nullif(v_item ->> 'price', '');
      if v_vprice is not null and v_vprice !~ '^\d{1,10}(\.\d{1,2})?$' then
        raise exception 'admin_save_product: invalid variant price' using errcode = '22023';
      end if;

      v_name_fr := concat_ws(' · ', 'Pack de ' || v_pack, 'SS' || v_ss);
      v_name_en := concat_ws(' · ', 'Pack of ' || v_pack, 'SS' || v_ss);
      v_vsku := case when v_sku is null then null
                     else v_sku || concat('-P' || v_pack, '-SS' || v_ss) end;
      if v_vsku is not null and v_vsku !~ '^[A-Z0-9][A-Z0-9-]{1,63}$' then
        raise exception 'admin_save_product: product SKU too long for its option SKUs' using errcode = '22023';
      end if;

      -- The same combination twice in one payload would silently merge.
      select pv.id into v_variant_id
        from public.product_variants pv
       where pv.product_id = v_id
         and pv.attributes -> 'pack' is not distinct from to_jsonb(v_pack)
         and pv.attributes -> 'ss'   is not distinct from to_jsonb(v_ss);
      if v_variant_id = any (v_variant_ids) then
        raise exception 'admin_save_product: duplicate option %', v_name_en using errcode = '22023';
      end if;

      if v_variant_id is not null then
        update public.product_variants
           set name       = v_name_fr,
               sku        = v_vsku,
               price      = v_vprice::numeric(12, 2),
               is_active  = true,
               position   = v_position
         where id = v_variant_id;
      else
        insert into public.product_variants (product_id, name, sku, attributes, price, is_active, position)
        values (v_id, v_name_fr, v_vsku,
                jsonb_strip_nulls(jsonb_build_object('pack', v_pack, 'ss', v_ss)),
                v_vprice::numeric(12, 2), true, v_position)
        returning id into v_variant_id;
      end if;

      insert into public.product_variant_translations (variant_id, locale, name, status)
      values (v_variant_id, 'en', v_name_en, 'published')
      on conflict (variant_id, locale) do update set name = excluded.name, status = 'published';

      update public.inventory_items
         set track_inventory     = coalesce((v_item ->> 'track_inventory')::boolean, track_inventory),
             quantity_on_hand    = coalesce((v_item ->> 'quantity_on_hand')::integer, quantity_on_hand),
             low_stock_threshold = coalesce((v_item ->> 'low_stock_threshold')::integer, low_stock_threshold)
       where variant_id = v_variant_id;
      if not found then
        insert into public.inventory_items (variant_id, track_inventory, quantity_on_hand, low_stock_threshold)
        values (v_variant_id,
                coalesce((v_item ->> 'track_inventory')::boolean, true),
                coalesce((v_item ->> 'quantity_on_hand')::integer, 0),
                coalesce((v_item ->> 'low_stock_threshold')::integer, 5));
      end if;

      v_variant_ids := array_append(v_variant_ids, v_variant_id);
      v_variant_id := null;
      v_position := v_position + 1;
    end loop;

    -- Options no longer offered: gone, unless an order remembers them.
    update public.product_variants pv
       set is_active = false
     where pv.product_id = v_id
       and not (pv.id = any (v_variant_ids))
       and exists (select 1 from public.order_items oi where oi.variant_id = pv.id);
    delete from public.product_variants pv
     where pv.product_id = v_id
       and not (pv.id = any (v_variant_ids))
       and not exists (select 1 from public.order_items oi where oi.variant_id = pv.id);
  end if;

  -- 3b. Any other kind of variant (only when the payload carries them) --------
  if v_custom is not null then
    -- Pack/SS options have their own editor, which derives names and SKUs
    -- from the grid; this list must not take them over.
    if exists (
      select 1 from public.product_variants pv
       where pv.product_id = v_id and pv.is_active
         and pv.attributes <> '{}'::jsonb
         and not exists (select 1 from jsonb_object_keys(pv.attributes) k where k not in ('pack', 'ss'))
    ) then
      raise exception 'admin_save_product: this product sells pack/stone-size options' using errcode = '22023';
    end if;

    -- Validate the whole list first, so the renames below never half-apply.
    for v_item in select value from jsonb_array_elements(v_custom) loop
      if jsonb_typeof(v_item) <> 'object' then
        raise exception 'admin_save_product: invalid variant' using errcode = '22023';
      end if;
      if coalesce(v_item ->> 'id', '') !~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' then
        raise exception 'admin_save_product: a variant needs an id' using errcode = '22023';
      end if;
      v_variant_id := (v_item ->> 'id')::uuid;
      if v_variant_id = any (v_custom_ids) then
        raise exception 'admin_save_product: duplicate variant %', v_variant_id using errcode = '22023';
      end if;
      select product_id into v_owner from public.product_variants where id = v_variant_id;
      if v_owner is not null and v_owner <> v_id then
        raise exception 'admin_save_product: variant % belongs to another product', v_variant_id using errcode = '22023';
      end if;
      v_owner := null;
      v_name_fr := btrim(coalesce(v_item ->> 'name', ''));
      if char_length(v_name_fr) not between 1 and 200 or char_length(btrim(coalesce(v_item ->> 'name_en', ''))) > 200 then
        raise exception 'admin_save_product: a variant needs a name of 1 to 200 characters' using errcode = '22023';
      end if;
      v_swatch := nullif(v_item ->> 'swatch', '');
      if v_swatch is not null and v_swatch !~ '^#[0-9a-f]{6}$' then
        raise exception 'admin_save_product: invalid swatch colour' using errcode = '22023';
      end if;
      v_vprice := nullif(v_item ->> 'price', '');
      if v_vprice is not null and v_vprice !~ '^\d{1,10}(\.\d{1,2})?$' then
        raise exception 'admin_save_product: invalid variant price' using errcode = '22023';
      end if;
      v_custom_ids := array_append(v_custom_ids, v_variant_id);
    end loop;
    v_variant_id := null;

    -- Variants no longer listed go first, so their SKUs and names are free for
    -- the list: deleted, unless an order remembers them (then deactivated).
    update public.product_variants pv
       set is_active = false
     where pv.product_id = v_id
       and not (pv.id = any (v_custom_ids))
       and exists (select 1 from public.order_items oi where oi.variant_id = pv.id);
    delete from public.product_variants pv
     where pv.product_id = v_id
       and not (pv.id = any (v_custom_ids))
       and not exists (select 1 from public.order_items oi where oi.variant_id = pv.id);

    -- product_variants_name_unique is not deferrable: swapping two names in one
    -- save would collide halfway. Listed variants first take their id as a
    -- placeholder name; a kept inactive variant holding a name the list reuses
    -- is renamed out of the way (its orders keep their own copy of the name).
    update public.product_variants
       set name = id::text
     where product_id = v_id and id = any (v_custom_ids);
    update public.product_variants pv
       set name = left(pv.name, 190) || ' #' || left(pv.id::text, 8)
     where pv.product_id = v_id
       and not (pv.id = any (v_custom_ids))
       and pv.name in (select btrim(e ->> 'name') from jsonb_array_elements(v_custom) e);

    v_sku := (select sku from public.products where id = v_id);
    v_position := 0;

    for v_item in select value from jsonb_array_elements(v_custom) loop
      v_variant_id := (v_item ->> 'id')::uuid;
      v_name_fr := btrim(v_item ->> 'name');
      v_name_en := nullif(btrim(coalesce(v_item ->> 'name_en', '')), '');
      v_swatch  := nullif(v_item ->> 'swatch', '');
      v_vprice  := nullif(v_item ->> 'price', '');

      if exists (select 1 from public.product_variants where id = v_variant_id) then
        update public.product_variants
           set name       = v_name_fr,
               attributes = case when v_swatch is null then attributes - 'swatch'
                                 else attributes || jsonb_build_object('swatch', v_swatch) end,
               price      = v_vprice::numeric(12, 2),
               is_active  = true,
               position   = v_position
         where id = v_variant_id
        returning sku into v_vsku;
      else
        v_vsku := null;
        insert into public.product_variants (id, product_id, name, attributes, price, is_active, position)
        values (v_variant_id, v_id, v_name_fr,
                case when v_swatch is null then '{}'::jsonb else jsonb_build_object('swatch', v_swatch) end,
                v_vprice::numeric(12, 2), true, v_position);
      end if;

      -- SKU: set once, from the product SKU and the French name in plain
      -- ASCII (no unaccent extension needed), unique with a suffix.
      if v_vsku is null and v_sku is not null then
        v_code := upper(btrim(regexp_replace(
          translate(replace(replace(replace(replace(v_name_fr, 'œ', 'oe'), 'Œ', 'OE'), 'æ', 'ae'), 'Æ', 'AE'),
                    'àâäáãåçéèêëíìîïñóòôöõúùûüýÿÀÂÄÁÃÅÇÉÈÊËÍÌÎÏÑÓÒÔÖÕÚÙÛÜÝŸ',
                    'aaaaaaceeeeiiiinooooouuuuyyAAAAAACEEEEIIIINOOOOOUUUUYY'),
          '[^A-Za-z0-9]+', '-', 'g'), '-'));
        if v_code = '' then
          v_code := 'V' || (v_position + 1);
        end if;
        v_base := rtrim(left(v_sku || '-' || v_code, 60), '-');
        v_vsku := v_base;
        v_n := 1;
        while exists (select 1 from public.product_variants where sku = v_vsku and id <> v_variant_id) loop
          v_n := v_n + 1;
          v_vsku := v_base || '-' || v_n;
        end loop;
        update public.product_variants set sku = v_vsku where id = v_variant_id;
      end if;

      if v_name_en is not null then
        insert into public.product_variant_translations (variant_id, locale, name, status)
        values (v_variant_id, 'en', v_name_en, 'published')
        on conflict (variant_id, locale) do update set name = excluded.name, status = 'published';
      else
        delete from public.product_variant_translations where variant_id = v_variant_id and locale = 'en';
      end if;

      update public.inventory_items
         set track_inventory     = coalesce((v_item ->> 'track_inventory')::boolean, track_inventory),
             quantity_on_hand    = coalesce((v_item ->> 'quantity_on_hand')::integer, quantity_on_hand),
             low_stock_threshold = coalesce((v_item ->> 'low_stock_threshold')::integer, low_stock_threshold)
       where variant_id = v_variant_id;
      if not found then
        insert into public.inventory_items (variant_id, track_inventory, quantity_on_hand, low_stock_threshold)
        values (v_variant_id,
                coalesce((v_item ->> 'track_inventory')::boolean, true),
                coalesce((v_item ->> 'quantity_on_hand')::integer, 0),
                coalesce((v_item ->> 'low_stock_threshold')::integer, 5));
      end if;

      v_variant_id := null;
      v_position := v_position + 1;
    end loop;
  end if;

  -- 4. Stock: one inventory row per product without active variants ---------
  --    A product with active variants keeps its stock on each variant (see
  --    step 3), and a digital product has none; both are left alone.
  if exists (select 1 from public.product_variants where product_id = v_id and is_active)
     or exists (select 1 from public.products where id = v_id and product_type = 'digital') then
    v_inventory := null;
  end if;

  if v_inventory is not null then
    update public.inventory_items
       set track_inventory     = coalesce((v_inventory ->> 'track_inventory')::boolean, track_inventory),
           quantity_on_hand    = coalesce((v_inventory ->> 'quantity_on_hand')::integer, quantity_on_hand),
           low_stock_threshold = coalesce((v_inventory ->> 'low_stock_threshold')::integer, low_stock_threshold),
           availability        = coalesce(v_inventory ->> 'availability', availability)
     where product_id = v_id;
    if not found then
      insert into public.inventory_items
        (product_id, track_inventory, quantity_on_hand, low_stock_threshold, availability)
      values
        (v_id,
         coalesce((v_inventory ->> 'track_inventory')::boolean, true),
         coalesce((v_inventory ->> 'quantity_on_hand')::integer, 0),
         coalesce((v_inventory ->> 'low_stock_threshold')::integer, 5),
         coalesce(v_inventory ->> 'availability', 'in_stock'));
    end if;
  end if;

  -- 5. Media: the payload is the complete, ordered list ------------------------
  v_position := 0;
  v_keep := array(
    select (e ->> 'id')::uuid
      from jsonb_array_elements(v_media) e
     where coalesce(e ->> 'id', '') <> ''
  );

  with gone as (
    delete from public.product_media
     where product_id = v_id and not (id = any (v_keep))
    returning storage_path
  )
  select array_agg(storage_path) into v_removed from gone;

  -- One primary per product (partial unique index): clear before re-setting.
  update public.product_media set is_primary = false where product_id = v_id and is_primary;

  for v_item in select value from jsonb_array_elements(v_media) loop
    -- The variant a photo shows: only a variant of this very product.
    v_media_variant := nullif(v_item ->> 'variant_id', '')::uuid;
    if v_media_variant is not null
       and not exists (select 1 from public.product_variants where id = v_media_variant and product_id = v_id) then
      raise exception 'admin_save_product: media variant % does not belong to this product', v_media_variant
        using errcode = '22023';
    end if;

    if coalesce(v_item ->> 'id', '') <> '' then
      update public.product_media
         set position   = v_position,
             is_primary = (v_position = 0),
             alt_text   = nullif(v_item ->> 'alt_fr', ''),
             variant_id = case when v_item ? 'variant_id' then v_media_variant else variant_id end
       where id = (v_item ->> 'id')::uuid and product_id = v_id
      returning id into v_media_id;
      if v_media_id is null then
        raise exception 'admin_save_product: media % does not belong to this product', v_item ->> 'id'
          using errcode = '22023';
      end if;
    else
      if coalesce(v_item ->> 'storage_path', '') !~ '^products/[A-Za-z0-9._/-]+$' then
        raise exception 'admin_save_product: invalid storage path' using errcode = '22023';
      end if;
      insert into public.product_media (product_id, variant_id, storage_path, alt_text, position, is_primary)
      values (v_id, v_media_variant, v_item ->> 'storage_path', nullif(v_item ->> 'alt_fr', ''), v_position, v_position = 0)
      returning id into v_media_id;
    end if;

    if coalesce(trim(v_item ->> 'alt_en'), '') <> '' then
      insert into public.product_media_translations (media_id, locale, alt_text, status)
      values (v_media_id, 'en', v_item ->> 'alt_en', 'published')
      on conflict (media_id, locale) do update
         set alt_text = excluded.alt_text, status = 'published';
    else
      delete from public.product_media_translations where media_id = v_media_id and locale = 'en';
    end if;

    v_media_id := null;
    v_position := v_position + 1;
  end loop;

  return jsonb_build_object(
    'id', v_id,
    'slug', (select slug from public.products where id = v_id),
    'removed_paths', to_jsonb(coalesce(array(
      select distinct path
        from unnest(v_removed) as path
       where path like 'products/%'
         and not exists (select 1 from public.product_media m where m.storage_path = path)
    ), '{}'::text[]))
  ) || case when v_variants is not null
            then jsonb_build_object('variants', to_jsonb(v_variant_ids))
            else '{}'::jsonb end
    || case when v_custom is not null
            then jsonb_build_object('custom_variants', to_jsonb(v_custom_ids))
            else '{}'::jsonb end;
end;
$$;

comment on function public.admin_save_product(jsonb) is
  'Back office: create/update a product with its English translation, stock, media and (optional) either pack (1–10 000 stones) × stone-size options or a free list of variants (colours, boxes…) with their photos, in one transaction. SECURITY INVOKER — RLS applies.';
